In [10]:
%matplotlib widget
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import ttest_ind

In [15]:
table_full = pd.read_excel("2022_CarbonExperiment.xlsx",sheet_name="harvest")

In [17]:
table_full

,#,treatment,fungus,start,crossed,harvest,days until harvest,fresh root [g],dry root [mg],agar root[g],agar left [g],agar right [g],Remarks
0,860,200C,A5,2021-12-21,2022-03-17 00:00:00,2022-04-29 00:00:00,43,1.822,111,18.710,12.250,12.990,NaN
1,982,100C,C2,2021-12-22,2022-03-15 00:00:00,2022-04-29 00:00:00,45,2.084,81,17.835,11.918,12.757,NaN
2,991,100C,C2,2021-12-22,2022-03-25 00:00:00,2022-05-09 00:00:00,45,1.760,87,18.420,12.220,12.790,NaN
3,938,200C,A5,2021-12-22,2022-03-25 00:00:00,2022-05-09 00:00:00,45,1.580,120,17.650,13.010,11.530,NaN
4,R70,100C,A5,2021-12-10,2022-03-23 00:00:00,2022-05-09 00:00:00,47,1.753,79,16.560,11.490,12.570,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,106,100C,A5,2022-06-22,2022-08-26 00:00:00,2022-10-21 00:00:00,56,2.216,87,19.536,11.930,12.631,NaN
70,109,100C,A5,2022-06-22,2022-08-29 00:00:00,2022-10-21 00:00:00,53,2.727,114,18.890,15.586,12.940,NaN
71,140,30C,A5,2022-07-06,2022-08-26 00:00:00,2022-10-21 00:00:00,56,2.022,66,18.320,12.262,14.017,NaN
72,94,100C,A5,2022-06-22,2022-09-09 00:00:00,2022-10-25 00:00:00,46,1.862,88,16.678,12.754,12.980,NaN
73,144,30C,A5,2022-07-06,2022-09-19 00:00:00,2022-11-07 00:00:00,49,1.968,71,19.070,12.451,13.103,NaN

In [ ]:
%matplotlib widget

table = table_full.loc[table_full['fungus']=='C2']
y='dry root [mg]'
sns.boxplot(x='treatment', y='dry root [mg]', data=table)

# Calculate significance between each pair of categories
categories = table['treatment'].unique()
for i in range(len(categories)):
    for j in range(i+1, len(categories)):
        cat1 = categories[i]
        cat2 = categories[j]
        values1 = table[table['treatment'] == cat1][y]
        values2 = table[table['treatment'] == cat2][y]
        t_stat, p_value = ttest_ind(values1, values2)
        if p_value < 0.05:
            print(p_value,cat1,cat2)
            # Add an asterisk to indicate significance
            x_pos = i + (j-i)/2
            y_pos = max(values1.max(), values2.max()) + 1
            plt.text(x_pos, y_pos, '*', ha='center', va='bottom')

# Set labels and title
plt.xlabel('treatment')
plt.ylabel(y)
plt.title('Boxplot with Significance')

# Show the plot
plt.show()